# Node.js

trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn build 
  workingDirectory: static-site-azure-app-service
  displayName: 'yarn install and build'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'static-site-azure-app-service/build'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    OverWrite: true
  displayName: 'Copy output files'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish output files'
